# Generated by mac-bootstrap — do not edit manually
# Regenerate with: make brewfile

# CLI tools
brew "mas"
brew "cocoapods"
brew "gh"

# Applications (casks)
cask "google-chrome"
cask "chatgpt"
cask "visual-studio-code"
cask "iterm2"
cask "whatsapp"
cask "telegram"
cask "logi-options+"
cask "1password"
