# Generated by mac-bootstrap — do not edit manually
# Regenerate with: make brewfile
# Last updated: 2026-06-30 22:41:19

# CLI tools
brew "mas"
brew "cocoapods"
brew "gh"
brew "dockutil"

# Applications (casks)
cask "google-chrome"
cask "chatgpt"
cask "visual-studio-code"
cask "iterm2"
cask "whatsapp"
cask "telegram"
cask "logi-options+"
cask "1password"
